### ISSUE TITLE
Bug located in dependabot setup

### ISSUE THREAD

**Issue by swilson-work** [ansys/pyturbogrid#55]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Dependabot is not checking all of the dependencies in pyproject.toml. It appears to check the first one and then stop. It never produces PRs for the other dependencies e.g. the documentation libraries.
So far as I know, it has never worked successfully, so the most likely cause of the error is incomplete/incorrect setup of dependabot.

### 📝 Steps to reproduce

Run dependabot on the project e.g. In the project, go to the Insights tab, select Dependency Graph, go to the Dependabot tab and asked to recheck pyproject.toml (by clicking on "Last checked ...").
Look at the output and notice that it only checks for ansys-turbogrid-api and doesn't check the subsequent dependencies.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23.2

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
Irrelevant, as this applies to the GitHub workflows not a local installation.
```

**Comment by Acohen-work** [comment]
This has been resolved
