### ISSUE TITLE
Modify the Documentation Logo

### ISSUE THREAD

**Issue by dnwillia-work** [ansys/pyturbogrid#76]
### Description of the modifications

The new PyAnsys logo is not being used by turbogrid:

https://turbogrid.docs.pyansys.com/version/stable/

See, PyFluent or PyAnsys-Units for instance

https://fluent.docs.pyansys.com/version/stable/
https://units.docs.pyansys.com/version/stable/

This can be had if you upgrade to the new logos.

https://github.com/ansys/pyansys-units/blob/a897ba3f051b2696e1c3f39effd4115012be376a/doc/source/conf.py#L5

**Comment by zlilek-work** [comment]
We will fix this, we are out of sync.

**Comment by zlilek-work** [comment]
Fixed with #77
